version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: async_redis_broker
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: async_router_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    environment:
      # We override localhost with the service name 'redis' for Docker-to-Docker network routing
      - REDIS_BROKER_URL=redis://redis:6379/0
      - REDIS_BACKEND_URL=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    build: .
    container_name: async_router_worker
    command: celery -A app.tasks.celery_app worker --loglevel=info
    volumes:
      - .:/code
    environment:
      - REDIS_BROKER_URL=redis://redis:6379/0
      - REDIS_BACKEND_URL=redis://redis:6379/0
    depends_on:
      - redis